#!/bin/bash

## Files & directories
# Create necessary directories
mkdir -p /var/www/html/uit-web/
mkdir -p /var/www/html/uit-web/transcode

# Static image content
if [[ ! -f /var/www/html/uit-web/favicon.png ]]; then
    wget 'https://uh.edu/favicon.png' --output-document /var/www/html/uit-web/favicon.png
fi
if [[ ! -f  /var/www/html/uit-web/images/uh-logo.png ]]; then
    wget 'http://www.sa.uh.edu/brand/_img/uh-wide-full-color-rgb.png' --output-document=/var/www/html/uit-web/images/uh-logo.png
fi

# Transpile
sudo -u cameron npx tsgo --project /var/www/html/uit-web/ts/tsconfig.json


## File permissions
chown uitweb:uit /var/www/html/uit-web -R
find /var/www/html/uit-web -type d -exec chmod 750 {} \;
find /var/www/html/uit-web -type f -exec chmod 660 {} \;
chmod 770 /var/www/html/uit-web/js/
chmod 770 /var/www/html/uit-web/ts/