-- SQL user creation
CREATE OR REPLACE PROCEDURE sqlCreateUsers()
LANGUAGE SQL
AS $$

CREATE USER cameron WITH SUPERUSER CREATEDB CREATEROLE PASSWORD 'UHouston!';

CREATE USER uitclient PASSWORD 'UHouston!';

CREATE USER uitweb PASSWORD 'UHouston!';

$$;

-- SQL permissions
CREATE OR REPLACE PROCEDURE sqlPermissions()
LANGUAGE SQL
AS $$

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO cameron WITH GRANT OPTION;
GRANT EXECUTE ON ALL PROCEDURES IN SCHEMA public TO cameron;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO cameron;

GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO uitclient;
GRANT EXECUTE ON ALL PROCEDURES IN SCHEMA public TO uitclient;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO uitclient;

GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO uitweb;
GRANT DELETE ON client_images TO uitweb;
GRANT EXECUTE ON ALL PROCEDURES IN SCHEMA public TO uitweb;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO uitweb;

$$;

CREATE OR REPLACE FUNCTION locationFormatting(location VARCHAR(128)) 
RETURNS VARCHAR(128) AS $$
BEGIN
  RETURN CASE
    WHEN REGEXP_MATCH(location, '^.{1}$') IS NOT NULL THEN UPPER(location)
    ELSE location
  END;
END;
$$ LANGUAGE plpgsql;

